name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
          
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.11.1

    - name: Login Docker
      uses: docker/login-action@v3.6.0
      with:
        username: caiotbraga
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: caiotbraga/go_ci:${{github.ref_name}}
          
