name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
          
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.11.1

    - name: login Docker
      uses: docker/login-action@v3.6.0
      with:
        username: caiotbraga
        password: ${{ secrets.DOCKER_PASSWORD }}
